// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeb_TranQuocHuy.Models;

namespace TestWeb_TranQuocHuy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeb_TranQuocHuy.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantilty")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Huy",
                            Price = 32300m,
                            Quantilty = 9,
                            Title = "Lập trình web"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Phu",
                            Price = 2300m,
                            Quantilty = 12,
                            Title = "Cấu trúc dữ liệu và giải thuật"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Huy",
                            Price = 5300m,
                            Quantilty = 5,
                            Title = "Kỹ thuật lập trình"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Phu",
                            Price = 3300m,
                            Quantilty = 2,
                            Title = "Lập trình Java coer"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Huy",
                            Price = 1300m,
                            Quantilty = 9,
                            Title = "Cơ sở dữ liệu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
